name: Create Pull Request

on:
  workflow_call:
    inputs:
      destination-branch:
        description: 'The branch base to be merged into'
        required: false
        default: staging
        type: string
      hotfix-destination-branch:
        description: 'The branch base to be merged into from a hotfix'
        required: false
        default: main
        type: string

jobs:
  lint-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch values
        id: get-branch
        run: |
          split=(${GITHUB_REF_NAME//\// })
          indexjira=0
          indexdescription=1
          JIRA_LABEL=${split[$indexjira]}
          DESCRIPTION=${split[$indexdescription]}

          # Valida se o nome da branch segue o padrão esperado
          if [[ ! $GITHUB_REF_NAME =~ ^[A-Z]+-[0-9]+\/[a-z0-9-]+$ ]]; then
            echo "Branch inválida! O formato deve ser <id-da-sua-tarefa>/<super-resumo-da-feature>, por exemplo: TL-100/create-post-api"
            exit 1
          fi

          TARGET="${{ inputs.destination-branch }}"
          IS_VALID_BRANCH=true
          TITLEHF=""

          echo "jira-label=$JIRA_LABEL" >> $GITHUB_ENV
          echo "description=$DESCRIPTION" >> $GITHUB_ENV
          echo "target=$TARGET" >> $GITHUB_ENV
          echo "title-hotfix=$TITLEHF" >> $GITHUB_ENV

  create-initial-pr:
    runs-on: ubuntu-latest
    needs: lint-branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ github.token }}
          source_branch: ${{ github.ref_name }}
          destination_branch: ${{ env.target }}
          pr_title: ${{ github.ref_name }}
          pr_body: |
            ## Type of change

            - [ ] Bug fix (non-breaking change which fixes an issue)
            - [ ] New feature (non-breaking change which adds functionality)
            - [ ] Chore (documentation, packages, or tests updates, nothing that affect the final user directly)
            - [ ] Release (new version of the application - only for production)

            ## Description

            ...

            ## Screenshots

            ...

            ## Tasks

            - [task-id](task-link) or N/A

            ## Checklist

            - [ ] My changes have less than or equal 400 lines
            - [ ] I have performed a self-review of my own code
            - [ ] The existing tests and linter pass locally with my changes
            - [ ] I have commented my code in hard-to-understand areas (if applicable)
            - [ ] I have created tests for my fix or feature (if applicable)

            ## Dependencies

            This pull request has a dependency on the following others:

            - link-to-depency PR or N/A
          pr_assignee: ${{ github.event.sender.login }}
          pr_label: enhancement
          pr_allow_empty: false
