name: 'Create Pull Request'

on:
  push:
    branches:
      - 'DEVOPS-*/**'
      - 'DEV-*/**'
      - 'DevOps-*/**'


permissions:
  contents: read
  packages: write
  actions: write

jobs:
  create-pull-request:
    uses: ./github/workflows/create-pull-request.yml@main
    with:
      destination-branch: 'main'
