name: 'Sonarqube Scan'

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'Sonarqube token'
        required: true
      SONAR_HOST_URL:
        description: 'Sonarqube URL'
        required: true
      SONAR_ORGANIZATION:
        description: 'Sonarqube project key'
        required: true

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initial Sonar Scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

