name: 'Sonarqube Scan'

on:
  workflow_call:
    secrets:
      sonarqube_token:
        description: 'Sonarqube token'
        required: true
      sonarqube_url:
        description: 'Sonarqube URL'
        required: true
      sonarqube_project_key:
        description: 'Sonarqube project key'
        required: true
      sonarqube_organization:
        description: 'Sonarqube organization'
        required: true

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli.zip -d $HOME
          echo "$HOME/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH

      - name: Verify SonarQube Scanner Installation
        run: sonar-scanner --version

      - name: Run SonarQube scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=${{ inputs.sonarqube_project_key }} \
          -Dsonar.organization=${{ inputs.sonarqube_organization }} \
          -Dsonar.host.url=${{ inputs.sonarqube_url }} \
          -Dsonar.login=${{ inputs.sonarqube_token }}